run:
  timeout: 5m
  issues-exit-code: 1

linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  dupl:
    threshold: 100
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 3
  goimports:
    local-prefixes: github.com/jlaska/sqlite-operator
  govet:
    check-shadowing: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - misspell