version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell
    - unconvert
    - dupl
    - revive

  settings:
    revive:
      rules:
        - name: dot-imports
          disabled: true

  exclusions:
    rules:
      - linters:
          - revive
        text: "dot-imports"
        path: test/