version: "2"

run:
  timeout: 5m

linters:
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 3
    govet:
      enable:
        - shadow
    misspell:
      locale: US

  exclusions:
    rules:
      - linters:
          - dupl
          - misspell
        path: _test\.go

formatters:
  enable:
    - gofmt
    - goimports