apiVersion: v1
kind: Service
metadata:
  name: litestream-operator-webhook-service
  namespace: litestream-operator-system
spec:
  selector:
    control-plane: controller-manager
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
