apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sqlite-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sqlite-operator-manager-role
subjects:
- kind: ServiceAccount
  name: sqlite-operator-controller-manager
  namespace: sqlite-operator-system