apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sqlite-operator
  
namespace: sqlite-operator-system

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sqlite-operator
    app.kubernetes.io/part-of: sqlite-operator

resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- database.example.com_sqlitedbs.yaml

images:
- name: controller
  newName: quay.io/jlaska/sqlite-operator
  newTag: latest

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
