apiVersion: v1
kind: Service
metadata:
  name: sqlite-operator-controller-manager-metrics-service
  namespace: sqlite-operator-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager