apiVersion: database.example.com/v1
kind: SQLiteDB
metadata:
  labels:
    app.kubernetes.io/name: sqlite-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-sqlitedb
spec:
  databaseName: "sampledb"
  storageSize: "2Gi"
  replicas: 1
  initSQL: |
    CREATE TABLE users (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
    
    INSERT INTO users (name, email) VALUES 
      ('Alice', 'alice@example.com'),
      ('Bob', 'bob@example.com');
    
    CREATE TABLE posts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER,
      title TEXT NOT NULL,
      content TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users (id)
    );
  backupEnabled: true
  backupSchedule: "0 2 * * *"