name: Debug Quay Auth

on:
  workflow_dispatch:

env:
  REGISTRY: quay.io
  IMAGE_NAME: jlaska/sqlite-operator

jobs:
  debug-auth:
    runs-on: ubuntu-latest
    steps:
    - name: Test Quay.io Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Test Docker commands
      run: |
        echo "Testing docker login status..."
        docker system info | grep -E "(Username|Registry)"
        
        echo "Testing repository access..."
        docker pull alpine:latest
        docker tag alpine:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-auth
        
        echo "Testing push permissions..."
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-auth || echo "Push failed - checking specific error"